apiVersion: v1
kind: Pod
metadata:
  labels:
    run: cyber
  name: cyber  
spec:
  containers:
  - name: webserver
    image: nginx
    volumeMounts:
    - mountPath: /cyber
      name: primeiro-volume
    resources:
      limits:
        cpu: "0.5"
        memory: "256Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
  - name: redis
    image: redis:alpine
    resources:
      limits:
        cpu: "0.5"
        memory: "64Mi"
      requests:
        cpu: "0.25"
        memory: "32Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: primeiro-volume
    emptyDir:
      sizeLimit: "256Mi"
