apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: giropops
  name: giropops #nome do pod
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
    - mountPath: /giropops
      name: primeiro-emptydir
    resources:
      limits:
        cpu: "1" #é o maximo permitido
        memory: "128Mi"
      requests:
        cpu: "0.5" # vai subir com esse valor
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes: 
  - name: primeiro-emptydir
    emptyDir:
      sizeLimit: "256Mi"
